name: Go Build and Test CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: 'go.mod'

    - name: Install dependencies
      run: go mod download

    - name: Build application
      run: go build -v ./cmd/douyin-go/main.go

    - name: Run unit tests
      run: go test -v ./...
